[package]
name = "glslang"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Interface with glslang, the reference GLSL compiler."
build = "build.rs"

[build-dependencies]
hyper = "0.1"
